# Generated by Django 4.2.13 on 2024-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ikea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='item_id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('price', models.FloatField(max_length=100, verbose_name='price')),
                ('old_price', models.CharField(max_length=100, verbose_name='old_price')),
                ('sellable_online', models.BooleanField(max_length=10, verbose_name='sellable_online')),
                ('link', models.CharField(max_length=200, verbose_name='link')),
                ('other_colors', models.CharField(max_length=10, verbose_name='other_colors')),
                ('short_description', models.CharField(max_length=200, verbose_name='short_description')),
                ('designer', models.CharField(max_length=100, verbose_name='designer')),
                ('depth', models.IntegerField(verbose_name='depth')),
                ('height', models.IntegerField(verbose_name='height')),
                ('width', models.IntegerField(verbose_name='width')),
            ],
        ),
    ]
